package email

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, message
func (_m *MockSender) Send(ctx context.Context, message *Message) error {
	ret := _m.Called(ctx, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

var _ Sender = (*MockSender)(nil)
