//-----------------------------------------------------------------------------
// Copyright (c) 2017 Oracle and/or its affiliates.  All rights reserved.
// This program is free software: you can modify it and/or redistribute it
// under the terms of:
//
// (i)  the Universal Permissive License v 1.0 or at your option, any
//      later version (http://oss.oracle.com/licenses/upl); and/or
//
// (ii) the Apache License v 2.0. (http://www.apache.org/licenses/LICENSE-2.0)
//-----------------------------------------------------------------------------

package email

import mock "github.com/stretchr/testify/mock"
import ses "github.com/aws/aws-sdk-go/service/ses"

// MockSenderSESAPI is an autogenerated mock type for the SenderSESAPI type
type MockSenderSESAPI struct {
	mock.Mock
}

// SendEmail provides a mock function with given fields: _a0
func (_m *MockSenderSESAPI) SendEmail(_a0 *ses.SendEmailInput) (*ses.SendEmailOutput, error) {
	ret := _m.Called(_a0)

	var r0 *ses.SendEmailOutput
	if rf, ok := ret.Get(0).(func(*ses.SendEmailInput) *ses.SendEmailOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ses.SendEmailOutput)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ses.SendEmailInput) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

var _ SenderSESAPI = (*MockSenderSESAPI)(nil)
